source "https://rubygems.org"

ruby "2.6.0"
gem "sinatra", "~>2.0.8"
gem "sinatra-contrib"
gem "rack", ">= 1.6.12"
gem "rack-protection", ">= 1.5.5"
gem "erubis"
gem "rack-test"
gem "minitest"
gem "redcarpet"
gem "bcrypt"
gem "pry"